### ISSUE TITLE
Bug import coordinates

### ISSUE THREAD

**Issue by rsanchezgarc** [scipion-em/scipion-em#375]
https://github.com/scipion-em/scipion-em/blob/1d0beb11ea4606be50776c81fdb730a50481fb71/pwem/protocols/protocol_import/coordinates.py#L228

Hi, 

This line will make "mic_100_coords.start" match with mic_1.mrc, which is wrong.

I guess that the proper way of dealing with it will be to compare the maximum common substrings.

This is my dirty patch

```
    def getMatchingMic(self, coordFile, fileId):
        """ Given a coordinates file check if there is a micrograph
        that this files matches.
        """
        from difflib import SequenceMatcher
        micSet = self.inputMicrographs.get()

        if fileId is None:
            coordBase = pwutils.removeBaseExt(coordFile)
            matcher = SequenceMatcher(a=coordBase)
            best_match_size = -1
            best_match_micId = None
            for mic in micSet:
                micBase = pwutils.removeBaseExt(mic.getFileName())
                matcher.set_seq2(micBase)
                match = matcher.find_longest_match(alo=0, ahi=len(coordBase), blo=0, bhi=len(micBase))
                if match and match.size > best_match_size:
                    best_match_size = match.size
                    best_match_micId = mic.getObjId()
            if best_match_micId:
                #TODO: Update a cache to avoid searching for the best_match micrograph in the next getMatchingMic call
                return micSet[best_match_micId]
            else:
                return None
        else:
            return micSet[fileId]

```

**Comment by pconesa** [comment]
Thanks, and performance wise this is a killer.

**Comment by azazellochg** [comment]
why are we even checking "in"? Just coordBase == micBase should be enough. Any suffixes etc should not be allowed. That's how it's done by eman and relion outside scipion.

**Comment by rsanchezgarc** [comment]
I would leave the suffix capable functionality as a fallback method in case you don't find as many micrographs as coordinate files, just in case, but I agree, we should first assume coordBase == micBase and if it is not the case, then fallback to the slow case (that needs bug fixing)

**Comment by azazellochg** [comment]
I disagree. We should increase performance rather than losing users due to
slow "more smart" parsing. If coordBase != micBase then the coords are not
found.

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: ***@***.***

**Comment by pconesa** [comment]
Thanks, both.
The thing is that at least, due to import renaming, micBase has a complex set of prefixes. All this was triggered by the fact that some user was actually importing micrographs with the same name but in different folders!!

This lead us to have to differentiate both, and then we have that complex micname, in some import cases. I think this happens when we import from /some/path/*/Data/something/else/*.mrc

(I fail to find /reproduce an example now)

Thus the "relaxed" match.

Probably the safest approach would be to try first an exact match (most probable one) and if not try the relaxed one.

**Comment by pconesa** [comment]
In terms of performance, it will degrade only in the case the exact match does not happen, which I think is worth trying the relaxed one despite: performance degradation (shouldn't be much if refactored) and possible inaccuracy.

**Comment by azazellochg** [comment]
@pconesa could you point to import renaming? Here we are not comparing micnames, but filenames only

**Comment by azazellochg** [comment]
but you are right we do have _aligned_DW stuff after motioncor.

**Comment by pconesa** [comment]
I was referring to this --> https://github.com/scipion-em/scipion-em/blob/devel/pwem/protocols/protocol_import/images.py#L499

In general.. : 

I think "image filename" can't be warrantied to be unique, since there are protocols generating new file with prefixes, suffixes, and basically there wasn't a "rule" to keep the names the same.

For this we have, "micName" (in SPA) and recently TsId (in tomo) to "free the filename" from being the identifier.

So far, we should do all matching based on "micName" but in some cases this micname could have a complex perefix due to the code pointed by the above link.

Therefore, in the more complex case a micrograph could end up in it's runs folder linked as:

 folder_subfolder1_mic1.mrc
 folder_subfolder2_mic1.mrc

NOTE: mic1.mrc is repeated.


Under this circumstances, micname, i think becomes  "folder_subfolder1_mic1" ?

When importing coordinates,....we cannot go for a exact match. But also, it will be ambiguous cause mic1 appears twice.

**Comment by pconesa** [comment]
Use this issue to:

Avoid renaming files at import time if possible. This will prevent mismatch in most of the cases.
