### ISSUE TITLE
emantomo initial model, Z dimension error from ptcl from a subset

### ISSUE THREAD

**Issue by brodriguezdefrancisco** [scipion-em/scipion-em#380]
hello,

There is an error when performing an Initial model with Eman within scipion using imported particles from a "subset".
 
Example of particles:
64x64x64 pixels.
![image](https://user-images.githubusercontent.com/66826085/205031362-fa3c58f1-a7c7-4c9b-9bc3-446440164c4c.png)

The intermediate and final .hdf files, have problems in displaying the Z dimension (problem with header probably).

See image below with chimera displayed .hdf volume and highlighted dimensions. Note that the Z dimension says pixel one, should be 7.

![Screenshot from 2022-12-01 11-42-47](https://user-images.githubusercontent.com/66826085/205033101-9f6707f8-4377-45ac-948f-e52bdb8d9ac2.png)

When Scipion created the .mrc output. It shows the good reconstructed volume.

Thanks in advance.

Borja

**Comment by JorMaister** [comment]
Solved in the latest update

**Comment by pconesa** [comment]
Isn't this more an eman error?

**Comment by JorMaister** [comment]
There was a conversation not long ago in some slack channel about the HDF files and loading them with Chimera. With the updated version of the plugin it doesn't matter to us because even if the user decides to keep the HDF files, the sqlite and every EM entity generated with our protocols will be a MRC file.
